---
- name: Install Docker and Run Containers
  hosts: all
  become: yes

  vars_files:
    - containers.yml

  roles:
    # - role: install_docker
    # - role: run_containers
    - role: system_config
    - role: deployment
