global:
  scrape_interval: 15s # Default interval to scrape targets

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets:
          - "cadvisor:8080" # Scrape cAdvisor metrics

  - job_name: "prometheus"
    static_configs:
      - targets:
          - "prometheus:9090" # Scrape Prometheus's own metrics

  - job_name: "loki"
    static_configs:
      - targets:
          - "loki:3100" # Scrape Loki logs (optional, if Loki is added)
